apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
data:
    ENVIRONMENT: {{ .Values.backend.config.ENVIRONMENT | quote }}
    DB_HOST: {{ .Values.backend.config.DB_HOST | quote }}
    DB_PORT: {{ .Values.backend.config.DB_PORT | quote }}