apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    # 1. Triggers the AWS Load Balancer Controller
    kubernetes.io/ingress.class: alb
    # 2. Makes the ALB public-facing
    alb.ingress.kubernetes.io/scheme: internet-facing
    # 3. Routes traffic directly to the Pod IP addresses
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/name: {{ .Values.ingress.name }}
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}-service
            port:
              number: 80
