apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.name }}-credentials
type: Opaque
data:
  USERNAME: {{ .Values.mongo.credentials.USERNAME | b64enc | quote }}
  PASSWORD: {{ .Values.mongo.credentials.PASSWORD | b64enc | quote }}   